version: 0.2

phases:
  install:
    commands:
      - "export release=AmazonLinux"
      - "sudo dnf install -y dnf-plugins-core"
      - "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "sudo dnf install -y terraform"
    pre_build:
      commands:
        - terraform init
        
    build:
      commands:
        - terraform $TF_COMMAND --auto-approve
        
    post_build:
      commands:
        - echo terraform $TF_COMMAND completed on 'date'
