version: 0.2

phases:
  install:
    commands:     
      - "yum install -y yum-utils"
      - "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "yum -y install terraform"
    pre_build:
      commands:
        - terraform init
        
    build:
      commands:
        - terraform $TF_COMMAND --auto-approve
        
    post_build:
      commands:
        - echo terraform $TF_COMMAND completed on 'date'
