version: 0.2

phases:
  install:
    commands:
      - "yum clean all"
      - "yum update -y"
      - "sudo yum install -y yum-utils"
      - "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "sudo dnf install -y terraform"
    pre_build:
      commands:
        - terraform init
        
    build:
      commands:
        - terraform $TF_COMMAND --auto-approve
        
    post_build:
      commands:
        - echo terraform $TF_COMMAND completed on 'date'
